# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieOMDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieOMDB
	pod 'Moya'
	pod 'Kingfisher'

  target 'MovieOMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieOMDBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
